services:
  app:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      HOSTNAME: 0.0.0.0
      LOCAL_DATABASE_PATH: /app/.data/agenda
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - app_data:/app/.data
volumes:
  app_data:
